# Generated by Django 3.2.7 on 2021-10-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0016_alter_hospital_hospital_code'),
        ('invoices', '0002_remove_invoice_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hospital_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
            preserve_default=False,
        ),
    ]
