# Generated by Django 3.2.7 on 2021-11-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
