# Generated by Django 3.2.7 on 2021-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20211121_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=8),
        ),
    ]
