# Generated by Django 3.2.7 on 2021-11-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
