# Generated by Django 3.2.7 on 2021-11-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoice_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
