# Generated by Django 3.2.7 on 2021-11-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_invoice_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_total',
        ),
    ]
