# Generated by Django 3.2.7 on 2021-11-24 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_auto_20211123_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='created_date',
        ),
    ]
