# Generated by Django 3.2.7 on 2021-11-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_remove_invoice_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
