# Generated by Django 3.2.7 on 2021-09-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='clock_in_lunch',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='clock_out_lunch',
            field=models.TimeField(blank=True),
        ),
    ]
