# Generated by Django 3.2.7 on 2021-09-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20210921_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='total_hours_worked',
            field=models.IntegerField(default=0),
        ),
    ]
