# Generated by Django 3.2.7 on 2021-09-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_timesheet_total_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='total_hours_worked',
        ),
    ]
