# Generated by Django 3.2.7 on 2021-09-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_remove_timesheet_total_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='total_hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
