# Generated by Django 3.2.7 on 2021-10-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_alter_timesheet_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='invoice_number',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
