# Generated by Django 3.2.7 on 2021-10-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0015_remove_timesheet_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='invoice_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
