# Generated by Django 3.2.7 on 2021-11-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_status_date'),
        ('timesheet', '0018_timesheet_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='invoice_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
    ]
