# Generated by Django 3.2.7 on 2021-11-21 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_alter_invoice_invoice_number'),
        ('timesheet', '0019_alter_timesheet_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='invoice_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice'),
        ),
    ]
