# Generated by Django 3.2.7 on 2021-09-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('FL', 'Florida'), ('GA', 'Georgia')], max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('telephone', models.CharField(max_length=10)),
            ],
        ),
    ]
