# Generated by Django 3.2.7 on 2021-10-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_alter_hospital_hospital_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hospital_code',
        ),
    ]
