# Generated by Django 3.2.7 on 2021-10-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_remove_hospital_hospital_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_code',
            field=models.CharField(default='x', max_length=4),
        ),
    ]
