# Generated by Django 3.2.7 on 2021-10-06 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0012_alter_hospital_hospital_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_code',
            new_name='code',
        ),
    ]
