# Generated by Django 3.2.7 on 2021-11-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0016_alter_hospital_hospital_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='max_invoice_number',
            field=models.IntegerField(default=0),
        ),
    ]
